apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: dispatcher-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]